version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - "8080:8080"  # Jenkins web interface
      - "50000:50000"  # Jenkins agent communication
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-data:
