name: Build and Push Docker Images

on:
  push:
    branches:
      - feature/cicd
      - release-branch  # Trigger the workflow on push to the main branch

jobs:
  build-and-push-fe:
    name: Build and Push FE Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push FE Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: haqimazhar/devops-capstone-project-fe:latest

  build-and-push-be:
    name: Build and Push BE Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push BE Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services
        push: true
        tags: haqimazhar/devops-capstone-project-be:latest
